### ISSUE TITLE
Unintended centering

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site#13]
https://sprucecss.com/ui/page/auth/
![image](https://github.com/conedevelopment/sprucecss-site/assets/952007/684df53a-0b2b-4115-a025-e51e841ec8ab)

`.auth-screen__inner` centers the label.

Not found: https://github.com/search?q=org%3Aconedevelopment+%22Welcome+back%22&type=code

**Comment by adamlaki** [comment]
Nice catch Viktor, I've just made a fix for it Spruce CSS: https://github.com/conedevelopment/sprucecss/commit/31b0d0cb8b647da77815eeeff053a5d72f5469d0

Thank you!

**Comment by szepeviktor** [comment]
You're welcome.
