### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss-site#21]
@adamlaki There are two "separeted"-s.
https://github.com/search?q=repo%3Aconedevelopment%2Fsprucecss-site%20separeted&type=code

Using `typos` will spot these.

**Comment by szepeviktor** [comment]
And two "two value"-s.

**Comment by adamlaki** [comment]
Thanks, Viktor!

Can you send me a link for the `typos` package? I've started to rewrite this site in 11ty, and I want to add spell and link-checker tests.

**Comment by szepeviktor** [comment]
Here it is https://github.com/crate-ci/typos
